### ISSUE TITLE
Coud not record audio

### ISSUE THREAD

**Issue by a44281071** [sudo-nautilus/FFmpeg-Builds-Win32#24]
version: 4.4.x
target: win32

Could not record mic audio by command:

```
ffmpeg -f dshow -i audio="Micphone (HIK 720P Camera-Audio)" -f gdigrab -show_region 1 -framerate 6 -video_size cif -offset_x 10 -offset_y 20 -i desktop out22222.mp4
```

**Comment by sudo-nautilus** [comment]
Try recording only the audio (`ffmpeg -f dshow -i audio="Micphone (HIK 720P Camera-Audio)" out.mp3"`) and check if that works

**Comment by sudo-nautilus** [comment]
Uh,
Is there any other input devices available?
Try using a recent version (win32, gpl)

One more thing, you can use `obs-studio` to capture your desktop
