### ISSUE TITLE
No Auto-Builds since middle of August?

### ISSUE THREAD

**Issue by Barough** [sudo-nautilus/FFmpeg-Builds-Win32#26]
What happen with the daily auto-builds?

**Comment by sudo-nautilus** [comment]
@Barough Btw
https://github.com/BtbN/FFmpeg-Builds/issues/191

**Comment by Barough** [comment]
Great to see that the 32-bit builds is available again

**Comment by sudo-nautilus** [comment]
You can use the last build or maybe wait for 3 hours, I can re run the last build but I think the waiting will be worth it

**Comment by Barough** [comment]
I'll wait. Take your time.

**Comment by sudo-nautilus** [comment]
Well, they're back

**Comment by Barough** [comment]
Thanks a lot :)

**Comment by sudo-nautilus** [comment]
:)
