### ISSUE TITLE
Update repo

### ISSUE THREAD

**Issue by sudo-nautilus** [sudo-nautilus/FFmpeg-Builds-Win32#7]
Anyone know how to update the repo without opening/running git

**Comment by pzhlkj6612** [comment]
Hi. You mean update from the upstream repo (BtbN/FFmpeg-Builds)? Try this: https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/compare/master...BtbN:master .  
However, merge with a merge commit, merge after squashing and merge with rebase, none of these three functions can produce a clean commit history (fast-forward), even though you do synchronize the files on your branch. In other words, you cannot completely sync your fork with the upstream through GitHub web UI so far.

**Comment by sudo-nautilus** [comment]
Thanks,
I was playing with git for updating repo which is quite awful.
I'll try that

**Comment by sudo-nautilus** [comment]
Yeah but,
What you mean by `clean commit history` ?

**Comment by pzhlkj6612** [comment]
It will not be a fast-forward history, but diverged.  
Here is the test result in my repository.

Before:

```
Upstream: a - b  -  d  - - -  g
                \ /   \     /
                 c     e - f

Mine:     a - b
```

After:

```
Upstream: a - b  -  d  - - -  g
                \ /   \     /
                 c     e - f

Mine:     a - b - c' - e' - f'
```

The resulting files are the same; however, as you can see, the history starting from commit `b` is completely different after merging. It looks like commits `c'` , `e'` and `f'` are cherry-picked from the corresponding commits in the upstream, and all merge commits ( `d` and `g` ) are ignored. It's completely not a fast-forward push (or, not a sync).

Therefore, I think we still need to execute `git fetch upstream && git push mine upstream/master:master` locally.

**Comment by sudo-nautilus** [comment]
But we can still try :)

**Comment by sudo-nautilus** [comment]
Let's see,
I made a PR to Xi-PP who forked one of my repo and his/her was updated. No I remember
